== Preamble

=== Parts of ABIS

The Australian Biodiversity Information Standard (ABIS) is a multi-part standard and this document is its normative specification.

The other parts of ABIS are:

* *Overview Document*
** https://linked.data.gov.au/def/abis/overview
** A simple introduction to the concepts within ABIS
* *Profile Definition*
** The technical expression of ABIS as a standard that inherits from other standards
** This is available in human- and machine-readable forms
* *Models*
** ABIS is made of multiple models which are listed in the <<Model, Model Section>> but are published and maintained elsewhere
** Both human- and machine-readable forms of all ABIS models are available
* *Vocabularies*
** ABIS, and the modes it depends on, rely on many vocabularies
** These are listed in the <<Vocabularies, Vocabularies Section>> but are published and maintained elsewhere
* *Validators*
** Data 'shape' files that can be used with validation tooling to check conformance of data to ABIS
** These are listed in the <<Validation, Validation Section>> but are published and maintained elsewhere


=== Namespaces

[frame=none, grid=none, cols="1,3,3"]
|===
|Prefix | Namespace | Description
|*`abis:`* | *`https://linked.data.gov.au/def/abis/`* | *ABIS namespace* - for the Standard as a whole
|*`bdr:`* | *`https://linked.data.gov.au/dataset/bdr/`* | *BDR Dataset Namespace*
|`dcterms:` | `http://purl.org/dc/terms/` | Dublin Core Terms vocabulary namespace
|`ex:` | `+http://example.com/thing+` | Generic examples namespace - _does not resolve_
|`owl:` | `http://www.w3.org/2002/07/owl#` | Web Ontology Language ontology namespace
|`rdfs:` | `http://www.w3.org/2000/01/rdf-schema#` | RDF Schema ontology namespace
|`sosa:` | `http://www.w3.org/ns/sosa/` | Sensor, Observation, Sample, and Actuator ontology namespace
|`skos:` | `http://www.w3.org/2004/02/skos/core#` | Simple Knowledge Organization System (SKOS) ontology namespace
|`tern:` | `https://w3id.org/tern/ontologies/tern/` | TERN Ontology namespace
|`time:` | `http://www.w3.org/2006/time#` | Time Ontology in OWL namespace
|`void:` | `http://rdfs.org/ns/void#` | Vocabulary of Interlinked Data (VoID) ontology namespace
|`xsd:` | `http://www.w3.org/2001/XMLSchema#` | XML Schema Definitions ontology namespace
|===

A JSON-LD _context_ built from this namespaces table is available as another resource within the ABIS specification and is online at:

* https://linked.data.gov.au/def/abis/context.json

=== Terms & Definitions

[[ABIS]]
ABIS:: The Australian Biodiversity Standard - the data standard this document is about

[[BDR]]
BDR:: Biodiversity Data Repository - a data collection managed by the https://linked.data.gov.au/org/dcceew[Department of Climate Change, Energy and the Environment] that incorporates biodiversity observations from State & Territory jurisdictions and aims to incorporate non-government data too

[[IRI]]
IRI:: An https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier[Internationalized Resource Identifier] is a web address-style URL that is used as an identifier for something. It may be for a real-world object, e.g. https://linked.data.gov.au/dataset/qldgeofeatures/AnakieProvince identifies the Queensland Geological Feature Anakie Province or for data only, e.g. https://w3id.org/tern/ontologies/tern/Text which identifies the class of 'Text' - textual results - within the <<TERN Ontology>>.
+
IRIs do not have to resolve - go somewhere online when clicked - but they do have to follow all the rules for URLs, such as no spaces.

[[Class]]
Class:: Based on the mathematical notion of a _set_, within formal OWL modelling, a class is a set of objects exhibiting common properties. For example, the set of all people who are studying could be defined as being within a Student class.

[[KnowledgeGraph]]
Knowledge Graph:: A data holding that implements node-edge-node (graph) data structures. The 'knowledge' part is often taken to indicate that the graph contains refined information, not just pure, raw, data.

[[LinkedData]]
Linked Data:: A series of technologies and methodologies for the publication of data on the Internet. Uses <<RDF, RDF>> as its underlying data structure, <<OWL, OWL>> as its data model and the common mechanics of the Domain Name System (DNS) and the Hypertext Transfer Protocol (HTTP) to identify and share its data.

[[OWL]]
OWL:: The OWL 2 Web Ontology Language, informally OWL 2, is an ontology language for the Semantic Web with formally defined meaning. OWL 2 ontologies provide classes, properties, individuals, and data values and are stored as Semantic Web documents. OWL 2 ontologies can be used along with information written in RDF, and OWL 2 ontologies themselves are primarily exchanged as RDF documents. OWL

[[Predicate]]
Predicate:: Predicates, within formal OWL modelling, are the defined relations between objects of different classes (see <<Class, Class>>) and also between objects and simple data values such as numbers and dates. For example, if Person X "knows" Person Y, then we can use a predicate of _knows_ to relate them.
+
Frequently we use predicates already defined in existing ontologies. "knows", for example, is defined in the schema.org ontology <<SDO, SDO>> to be "The most generic bi-directional social/work relation".

[[RDF]]
RDF:: The Resource Description Framework (RDF) is a data structure for representing information on the Web. RDF is made of identified nodes linked by typed edges that form graphs. Node/edge/node associations are often called 'triples'.

[[SeamanticWeb]]
Semantic Web:: A vision of a machine-understandable Internet, created in the year 2000, and thought to be attainable through the use of Linked Data.

[[SPARQL]]
SPARQL:: SPARQL is a query language for RDF. SPARQL matches patterns within RDF data to extract subsets of a graph. The results of SPARQL queries can be subset graphs or data in tabular form.
