=== BDR Messages Requirements

The https://linked.data.gov.au/def/bdr-msg:[BDR Messages Ontology] defines a general message class object, `bdrm:Message`, and four subclasses of it that are to be used to convey _create_, _update_, _delete_, and _exists_ (existance check) messages to the Biodiversity Data Repository (BDR). The following Requirements specify the required _structure_ of BDRM messages only and not any requirements of Domain Model content with messages' payloads which are specified in the <<Domain Model Requirements>> above.

When ABIS content is send to the Biodiversity Data Repository, the BDR acts both as the storage of that content and also the authoritative identifier creator for instances of certain classes of resources in that content, namely:

* `bdrm:Message`
** and subclasses
* `tern:RDFDataset`
* `tern:Sampling` 
* `tern:Sample`
* `tern:Site`
* `tern:FeatureOfInterest`

`bdrm:CreateMessage` instances, used to create new content within the BDR, must use the designated placeholder IRI namespace, `http://createme.org/`, for instances of those classes, so that the BDR can replace them with ones it issues, except for `tern:RDFDataset` which they may either use `http://createme.org/` or pre-allocate via the dataset IRI allocation mechanism in the BDR Gateway (see http://gateway.dev.bdr.gov.au/allocate). The client requesting new content creation will receive responses from the BDR that indicate what the BDR IRIs ultimately issued for the given placeholder IRIs are. There are lots of examples of  `http://createme.org/` in use in the http://gateway.dev.bdr.gov.au[BDR Gateway].

==== Message Parts

[width=75%, frame=none, cols="1,5"]
|===
|Property | Value

|Identifier | link:https://linked.data.gov.au/def/abis/req/bdr-messages[`req:bdr-messages`]
|Label | BDR Message part
|Definition a| BDR messages must have at least one part, indicated with `dcterms:hasPart`
|Conformance Classes | link:https://linked.data.gov.au/def/abis/conformanceclass/bdr-messages[`cc:bdr-messages`]
|Source | BDR Gateway Messaging
|Validators | link:https://linked.data.gov.au/def/bdr-msg-shapes[`https://linked.data.gov.au/def/bdr-msg-shapes`]
|Examples | See the http://gateway.dev.bdr.gov.au[BDR Gateway]
|===

==== CreateMessage Createme IRIs

[width=75%, frame=none, cols="1,5"]
|===
|Property | Value

|Identifier | link:https://linked.data.gov.au/def/abis/req/create-createme[`req:create-createme`]
|Label | CreateMessage Createme IRIs
|Definition a| BDR Create messages must indicate parts with createme.org IRIs only

_All items requested to be created via a `bdrm:CreateMessage` must use the designated placeholder IRI namespace, `http://createme.org/`, for instances of classes to be created whose authoritative namespace is managed by the BDR system. This includes the classes `tern:Sampling`, `tern:Sampling`, `tern:Site` etc._
|Conformance Classes | link:https://linked.data.gov.au/def/abis/conformanceclass/bdr-messages[`cc:bdr-messages`]
|Source | BDR Gateway Messaging
|Validators | link:https://linked.data.gov.au/def/bdr-msg-shapes[`https://linked.data.gov.au/def/bdr-msg-shapes`]
|Examples | See <<Create Messages>> and the http://gateway.dev.bdr.gov.au[BDR Gateway]
|===

==== Update or Delete Message IRIs

[width=75%, frame=none, cols="1,5"]
|===
|Property | Value

|Identifier | link:https://linked.data.gov.au/def/abis/req/non-create-iris[`req:non-create-iris`]
|Label | CreateMessage Createme IRIs
|Definition a| BDR Update & Delete messages must indicate parts with BDR IRIs only

_All items requested to be Updated, Deleted or have their existance checked must be indicated with IRIs starting `https://linked.data.gov.au/dataset/bdr/`._
|Conformance Classes | link:https://linked.data.gov.au/def/abis/conformanceclass/bdr-messages[`cc:bdr-messages`]
|Source | BDR Gateway Messaging
|Validators | link:https://linked.data.gov.au/def/bdr-msg-shapes[`https://linked.data.gov.au/def/bdr-msg-shapes`]
|Examples | See the http://gateway.dev.bdr.gov.au[BDR Gateway]
|===

