== Introduction

This document contains general description of the https://linked.data.gov.au/def/abis[Australian Biodiversity Information Standard (ABIS)] and importantly a list of _requirements_ and groupings of requirements, _Conformance Classes_. Data must meet all the _requirements_ in _conformance classes_ to claim conformance to that _conformance class'_ part of the ABIS.

This document also lists all the parts of the ABIS which are its various ontologies, vocabularies and others that these depend on. These parts are listed in <<Annex A: ABIS Parts, Annex A: ABIS Parts>>.

=== Requirement and Conformance Class modelling

Each _requirement_ is defined with a table of values like this:

[width=25%, frame=none, grid=none]
|===
|Identifier | Prefixed IRI identifier
|Label | Short text
|Definition | Defining text
|Conformance Classes | Selected Conformance Class Identifiers
|Source | Notes on _requirement_ source
|Validators | Related SHACL validators
|Examples | Related RDF example data
|===

The https://en.wikipedia.org/wiki/Semantic_Web[Semantic Web] interpretation of the relation of each of those properties are to each requirement instance are:

[width=25%, frame=none, grid=none]
|===
|Property | Defining RDF predicate | Object type

|Identifier | `dcterms:identifier` | IRI
|Label | `skos:prefLabel` | text
|Definition | `skos:definition` | text
|Conformance Classes | `dcterms:isPartOf` | IRIs
|Source | `dcterms:source` or `dcterms:provenance` | IRI of an ABIS resource or text
|Validators | ??? | IRI of a `Resource Descriptor`
|Examples | `skos:example` | IRI of a `Resource Descriptor`
|===

See the <<Namespaces>> section below to understand the prefixes in the table above.

The following subsections define properties of the _requirements_ in detail.

==== Identifier

Each _requirement_ is identified with a unique identifier of the form `req:X`, where `req:` is a prefix for the IRI namespace `+<https://linked.data.gov.au/def/abis/req/>+` and `X` is a number, the number of the _requirement_.

The IRI namespace plus the number make the complete IRI of the _requirement_.

An IRI is an https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier[Internationalized Resource Identifier] which is a globally unique web address created within a managed namespace that resolves to the element it identifies

==== Labeled

Each _requirement_ is named with a short form of its definition, to assist with human referencing.

==== Definition

Each _requirement_ is defined in human-readable terms but with references to data elements modelled according to ontologies defined using the https://www.w3.org/TR/owl2-overview/[Web Ontology Language (OWL)] since the _target models_ of the ABIS are themselves OWL Ontologies.

NOTE: If there are differences between derivatives of this specification, including the ABIS validator, these definitions take precendence

==== Conformance Classes list

Each _requirement_ is categorised within one or more "Conformance Classes" which are defined bundles of requrirements. Within the ABIS, the Conformance Classes form modules which data may conform to individually.

Each _requirement_ needs to indicate its Conformance Classes by linking to them.

==== Contains source notes

Each _requirement_ contains source notes  what motivated the _requirement_'s definition, including references to source documents or other ABIS artifacts, such as ontologies.

==== Related validators

Each _requirement_ contains references to individual, identified, data validation _shapes_ defined in the ABIS Profile's _validator_ used to validate https://www.w3.org/RDF/[Resource Description Framework (RDF)] data - the only form of data allowed to be used for ABIS data exchange.

The content of _validator_s is contained in the ABIS' _Validator_ resource.

NOTE: The validating _shapes_ are not 1:1 with these _requirements_ and that there are _requirements_ for which there are no _shapes_ - those _requirements_ that cannot be determined to have been met by inspecting data.

==== Canonical examples

For each _requirement_, references are given to at least two _canonical examples_ of RDF data that do (positive example) and don't (negative example) pass validation using the validators related to the _requirement_.

The content of the _canonical examples_, i.e. the examples' data, is contained in the ABIS' _Canonical Examples_ resource.
