== Vocabularies

Use of ABIS depends on many vocabularies from many different places. For example, observed _feature types_ may be indicated by use of http://linked.data.gov.au/def/tern-cv/db6d3a22-8bf4-4e27-a9a4-a49e228b6f52[atmosphere], http://linked.data.gov.au/def/tern-cv/237df7e1-2d92-4e9d-851e-28439bf5d8d8[biosphere] or http://linked.data.gov.au/def/tern-cv/8282fb22-4135-415c-8ca2-317860d102fb[land surface] taken from https://www.tern.org.au/[TERN]'s http://linked.data.gov.au/def/tern-cv/68af3d25-c801-4089-afff-cf701e2bd61d[Feature Type vocabulary].

Some uses of ABIS, such as for the submission of data to the <<BDR, BDR>>, require the use of particular vocabularies that aren't mandated for general ABIS use, for example the use of the https://linked.data.gov.au/dataset/bdr/datatypes[_BDR Datatypes_] vocabulary for special forms of identifiers. Mandates for particular vocabulary use are indicated by individual profiles of ABIS - see <<Profiles, Profiles>>.

Some <<Foreground Models>> within ABIS require the use of particular vocabularies, for example, the <<#TERNOntology, TERN Ontology>> mandates that a https://w3id.org/tern/ontologies/tern/FeatureOfInterest[tern:FeatureOfInterest] indicate a https://w3id.org/tern/ontologies/tern/featureType[tern:featureType] with the http://linked.data.gov.au/def/tern-cv/68af3d25-c801-4089-afff-cf701e2bd61d[Feature Type vocabulary].

=== Vocab Listing

While profiles of ABIS and its Component Model will list the vocabs they require for use, the BDR attempts to list all vocabularies known to be used by these at the:

* https://resources.bdr.gov.au/catalogues[BDR Catalogues home]
