== Profiles

A "profile" is a:

> A specification that constrains, extends, combines, or provides guidance or explanation about the usage of other specifications.
-- https://www.w3.org/TR/dx-prof/#dfn-profile[ref]

Profiles may comprise multiple parts such as their own specification rules, validation constraints, controlled vocabularies, and so on.

=== ABIS is a Profile

ABIS, itself, is a profile of many other specifications, as per the <<Model Dependency Hierarchy, Model Dependency Hierarchy>>.

ABIS is also made of multiple parts, as per the Section <<Parts of ABIS, Parts of ABIS>>.

=== Profiles of ABIS

Further profiles of ABIS may be made to constrain and/or extend its use.

Profile makers are able to define extended constraints on the use of ABIS to meet particular business needs. This can include constraining value ranges, vocabularies used and so on. Profile rules are entirely a matter for profile definers, however profiles must always ensure that any data valida according to them is also valid according to the standard being profiled.

Profiles of ABIS may be defined anywhere but profile creators are encouraged to list their profiles here by <<Metadata, contacting ABIS' maintainers>>.

The following profiles of ABIS are known to exist:

1. <<BDR Profile, BDR Profile>>

[[profile-bdr]]
=== BDR Profile

The BDR Profile of ABIS is presented in a stand-alone document, see **https://linked.data.gov.au/def/bdr-pr**.

This profile defines the requirements for data to be absorbed into the https://www.dcceew.gov.au/environment/epbc/publications/biodiversity-data-repository[Biodiversity Data Repository].

It contains a number of foreground models - for Project, Data Release etc. - not required for general ABIS use as well as its own vocabularies and requirements relating to identifiers for certain classes of object.

[NOTE]
====
Previously this document contained all the information about the BDR Profile here. This information is now all contained within the BDR Profile of ABIS' own document, linked to above.
====