== Validation

This model implements a validator for data claiming conformance to ABIS to test the claim. Since ABIS data _MUST_ be provided in RDF, only an RDF validator is available and other forms of validation are non-normative.

=== Multiple Validators

Just as the ABIS model is a collection of models and also inherits model elements from other models (see <<Multiple Models, Multiple Models>>), so too is the ABIS validator a collection of ABIS-created validators and inherited validation rules. For data to validly conform ABIS, it must also be valid according all these validators. Part use of ABIS may choose to be valid according to only some ABIS validators.

The following table lists all the validators relevant to ABIS and describes their roles.

[width="30%",cols="1,3,1"]
|===
| Validator | Description | Source

| ABIS Compounded Validator | All the validators relevant to ABIS, compounded into one | ABIS
| ABIS Validator | Validation rules implemented by ABIS only | ABIS
| Data Project Model Validator | Validation rules implemented by the <<Projects Model, Projects Model>> only | ABIS
| Data Release Model Validator | Validation rules implemented by the <<Data Release Model, Data Release Model>> only | ABIS

|===


=== Performing Validation