== Reasoning Rules

This section contains rules that ABIS-compliant systems must implement. The rules are machine executable rules that create new information from ABIS data based on logical, ontological, spatial and other reasoning.

=== How Rules Work


=== Rule List

[discrete]
==== Record Rule

This rule allows for the creation of <<abis:BiodiversityOccurrenceRecord, Record>> instances from <<TERN Ontology, TERN Ontology>> data that doesn't directly indicate such as class of object.

[discrete]
==== Spatial Reasoning

The following spatial reasoning rules will be applied to ABIS data.

[discrete]
===== Centroids and Bounding Boxes from Boundaries

[discrete]
===== `Datasets` containment of `Surveys`

[discrete]
===== `Surveys` containment of `Observations`

[discrete]
===== Inference of geometry literal datatypes from GeoSPARQL predicates

[discrete]
==== Temporal Reasoning

[discrete]
===== Inference of date/time literal datatypes from TIME predicates


#TODO: complete this section#