[[annex-f]]
== Annex C: Extended Examples

This following examples are all <<RDF, RDF>> data in the <<TURTLE, Turtle>> format.

=== C.1. TERN Ontology

These examples use <<TERNOntology, TERN Ontology>> elements only.

==== C.1.1 Validating

All these examples are loaded into the https://resources.bdr.gov.au/[BDR ABIS Resources] and may be validated online using the TERN Ontology validator which is also loaded there.

To validate these examples locally - on your own computer - you will need a validation tool installed. See the <<Validation, Validation Section>> for details. The example data file, the TERN Ontology validator and the TERN Ontology itself are all available from the ABIS repository:

|===
| File | Location | Validity

| TERN Ontology Validator | https://github.com/AusBIGG/abis/blob/master/models/tern.ttl | -
| TERN Ontology Model | https://github.com/AusBIGG/abis/tree/master/models/components/tern-model.ttl | -
| Example 01 data | https://github.com/AusBIGG/abis/tree/master/examples/tern-eg-01.ttl | valid
| Example 02 data | https://github.com/AusBIGG/abis/tree/master/examples/tern-eg-02.ttl | invalid
|===

If using the https://github.com/RDFLib/pySHACL[pySHACL] tool, the following command will validate the data using the files above:

----
pyshaclz -s tern-validator.ttl -e tern-ont.ttl tern-eg-01.ttl -f table
----

==== C.1.2 Example 01 - valid

This example is valid according to the TERN Ontology validator.

[source,turtle]
.TERN Ontology example 01 - valid
----
include::../examples/tern-eg-01.ttl[]
----

==== C.1.3 Example 02 - invalid

This example is the same data as the above but with several lines commented out (starting with `#`) which makes it invalid according to the TERN Ontology validator.

[source,turtle]
.TERN Ontology example 02 - invalid
----
include::../examples/tern-eg-02.ttl[]
----

Results from validating this example should indicate two Violations:

. The datatype for the value indicated by the `tern:resultDateTime` predicate on the object `ex:obs-01` is of an invalid datatype
* no datatype is given, so a string (`xsd:string`) is presumed but it should be an `xsd:date`, `xsd:dateTime` or `xsd:dateTimeStamp`
. `ex:obs-01` is missing a `geo:hasGeometry` predicate
. `ex:foi-01` is missing a `void:inDataset` predicate