= ABIS Overview
:toc: left
:table-stripes: even
:sectnums:

By Nicholas Car (nicholas.car@dcceew.gov.au) at DCCEEW, updated 16th Feb, 2024

This document will soon be a short overview of the https://linked.data.gov.au/def/abis[Australian Biodiversity Information Standard (ABIS)]. It is only one of many parts of ABIS and https://linked.data.gov.au/def/abis#_structure[all the parts are listed in ABIS].

== What is ABIS?

ABIS is a data standard that specifies how information about biodiversity is to be represented for exchange and use in Australia. 

It is a technical data standard and mandates a specific form of machine-readable information representation for data exchange: RDF (Resource Description Framework). RDF is "a standard model for data interchange on the Web"footnote:[https://www.w3.org/RDF/].

Use of the ABIS results in biodiversity information being formulated into data that can be validated against ABIS requirements in an automated way and the standard provides validators to verify data, see the https://linked.data.gov.au/def/abis#_validation[standard's Validation section].

ABIS implements a few domain-specific concepts itself but mostly re-uses existing models https://linked.data.gov.au/def/abis#_multiple_models[which it lists here].

== Who owns it?

_coming soon!_

== How do I use it?

_coming soon!_

== More help

ABIS is governed by https://linked.data.gov.au/org/ausbigg[Australian Biodiversity Information Governance Group (AusBIGG)] who is supported with technical management and data modelling by the Biodiversity Data Repository (BDR) Team within https://linked.data.gov.au/org/dcceew[the Department of Climate Change, Energy, the Environment and Water (DCCEEW)].

The BDR Team can be contacted on bdr@dcceew.gov.au.

Issue tracking of the ABIS standard is managed online at https://github.com/AusBIGG/abis/issues
