= ABIS Overview
:toc: left
:table-stripes: even
:sectnums:

By https://orcid.org/0000-0002-8742-7730[Nicholas Car]

This document will soon be a short overview of the https://linked.data.gov.au/def/abis[Australian Biodiversity Information Standard (ABIS)]. It is only one of many parts of ABIS and https://linked.data.gov.au/def/abis#_structure[all the parts are listed in ABIS].

== What is ABIS?

ABIS is a data standard that specifies how information about biodiversity is to be represented for exchange and use in Australia. 

It is a technical data standard and mandates a specific form of machine-readable information representation for data exchange: RDF (Resource Description Framework). RDF is "a standard model for data interchange on the Web"footnote:[https://www.w3.org/RDF/].

Use of the ABIS results in biodiversity information being formulated into data that can be validated against ABIS requirements in an automated way and the standard provides validators to verify data, see the https://linked.data.gov.au/def/abis#_validation[standard's Validation section].

ABIS implements a few domain-specific concepts itself but mostly re-uses existing models https://linked.data.gov.au/def/abis#_multiple_models[which it lists here].

== How do I use it?

_coming soon!_