name: Auto-build HTML

on: 
  push: 
      branches:
          - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Build
      working-directory: ./
      run: |
        echo "Making deployment dir - docs/"
        mkdir docs
        #
        echo "Add README to docs/"
        cp README.md docs/        
        sudo apt-get install asciidoctor ruby -y
        #
        echo "Add standard to docs/"
        asciidoctor standard/_standard.adoc -o docs/standard.html
        cp -r standard/img docs/
        sed -i 's#img src="#img src="https://ausbigg.github.io/abis/#' docs/standard.html        
        #
        echo "Add standard RDF to docs/"
        cp rdf/profile.ttl docs/
        #
        echo "Add Specification to docs/"   
        asciidoctor specification/_specification.adoc -o docs/specification.html
        cp -r specification/img docs/
        sed -i 's#img src="#img src="https://ausbigg.github.io/abis/#' docs/specification.html
        #
        echo "Add Overview to docs/"   
        asciidoctor overview/_overview.adoc -o docs/overview.html
        cp -r overview/*.png docs/
        sed -i 's#img src="#img src="https://ausbigg.github.io/abis/#' docs/overview.html        
        #
        echo "Add JSON-LD Context to docs/"
        cp context.json docs/
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
         BRANCH: gh-pages
         FOLDER: docs