name: Auto-buid HTML

on: 
  push: 
      branches:
          - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Replace img links
      working-directory: ./
      run: |
        sudo apt-get install asciidoctor ruby -y
        asciidoctor standard/_standard.adoc -o standard.html
        sed -i 's#img src="#img src="https://surroundaustralia.github.io/ndes#' standard.html        
        asciidoctor specification/_specification.adoc -o specification.html
        sed -i 's#img src="#img src="https://surroundaustralia.github.io/ndes#' specification.html