name: Auto-build HTML

on: 
  push: 
      branches:
          - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Build
      working-directory: ./
      run: |
        echo "Making deployment dir - docs/"
        mkdir docs
        #
        echo "Add README to docs/"
        cp README.md docs/        
        sudo apt-get install asciidoctor ruby -y
        #
        echo "Add standard to docs/"
        asciidoctor standard/_standard.adoc -o docs/standard.html
        cp -r standard/img docs/
        sed -i 's#img src="#img src="https://ausbigg.github.io/abis/#' docs/standard.html        
        #
        echo "Add profile RDF to docs/"
        cp profile.ttl docs/
        #
        echo "Add Specification to docs/"   
        asciidoctor spec/00-master.adoc -o docs/specification.html
        cp -r spec/img docs/
        sed -i 's#img src="#img src="https://ausbigg.github.io/abis/#' docs/specification.html
        #
        echo "Add Overview to docs/"   
        asciidoctor overview/_overview.adoc -o docs/overview.html
        cp -r overview/*.png docs/
        sed -i 's#img src="#img src="https://ausbigg.github.io/abis/#' docs/overview.html        
        #
        echo "Add JSON-LD Context to docs/"
        cp context.json docs/
        #
        echo "Add Component Models to docs/"
        cp schemas/components/data-release.ttl docs/
        cp schemas/components/projects.ttl docs/
        cp schemas/components/tern-ont.ttl docs/
        #
        echo "Add profiles of ABIS to docs/"
        cp profiles/bdr/profile.ttl docs/bdr.ttl
        #
        echo "Add validator to docs/"
        cp validators/*.ttl docs/
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
         BRANCH: gh-pages
         FOLDER: docs