name: Auto-buid HTML

on: 
  push: 
      branches:
          - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Build
      working-directory: ./
      run: |
        echo "Making deployment dir - docs/"
        mkdir docs
        echo "Add README to docs/"
        cp README.md docs/        
        sudo apt-get install asciidoctor ruby -y
        echo "Add standard to docs/"
        asciidoctor standard/_standard.adoc -o docs/standard.html
        sed -i 's#img src="#img src="https://surroundaustralia.github.io/ndes/#' docs/standard.html        
        echo "Add specification to docs/"
        asciidoctor specification/_specification.adoc -o docs/specification.html
        sed -i 's#img src="#img src="https://surroundaustralia.github.io/ndes/#' docs/specification.html
        echo "Add images to docs/"
        cp -r img docs/
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
         BRANCH: gh-pages
         FOLDER: docs